version: '3'

services:
  dump1090:
    build:
      context: dump1090
    ports:
      - 8080:8080/tcp
    devices:
      - /dev/bus/usb
    restart: unless-stopped

  piaware:
    build:
      context: piaware
    env_file: 'flightaware_credentials.txt'
    environment:
      - BEAST_PORT_30005_TCP_ADDR=dump1090
    restart: unless-stopped

  radarbox:
    build:
      context: radarbox
    env_file: 'radarbox_credentials.txt'
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
    restart: unless-stopped

  opensky:
    image: opensky:latest
    restart: unless-stopped

  flightradar24:
    build:
      context: flightradar24
    restart: unless-stopped


  adsbexchange-feed:
    environment:
      - 'INPUT=decoder:30005'
    links:
      - 'dump1090:decoder'
    image: marcelstoer/adsbexchange-docker-feed
    restart: unless-stopped

  adsbexchange-mlat:
    env_file: 'adsbexchange_mlat_properties.txt'
    environment:
      - 'INPUT=decoder:30005'
      - 'MLAT_RESULTS=decoder:30104'
    links:
      - 'dump1090:decoder'
    image: marcelstoer/adsbexchange-docker-mlat
    restart: unless-stopped

  adsbhub:
    image: jraviles/adsbhub
    restart: unless-stopped
